# Puerto dinámico obligatorio para Render (Evita el Timed Out)
server.port=${PORT:8080}

# Conexión moderna para Spring Boot 3+
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://Luis_Diaz:TnKDdqPtru28cxl8@legado-valientes-cluste.3gf5uum.mongodb.net/?appName=Legado-valientes-cluster}
spring.mongodb.database=legado_valientes