# Puerto dinámico para Render (¡Obligatorio para que no falle!)
server.port=${PORT:8080}

# Conexión a MongoDB con variable de entorno y fallback local
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://Luis_Diaz:TnKDdqPtru28cxl8@legado-valientes-cluste.3gf5uum.mongodb.net/?appName=Legado-valientes-cluster}
spring.mongodb.database=legado_valientes